[project]
name = "deep-research-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.8.0",
    "openai-agents>=0.5.1",
    "resend>=2.19.0",
    "tavily>=1.1.0",
]
